{
    "Target": {
        "EntitySet": "ErrorArchive",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "QueryOptions":"/SAPAssetManager/Rules/Common/ErrorArchiveQueryOptions.js"
    },
    "OnSuccess": "/SAPAssetManager/Actions/CreateUpdateDelete/DeleteEntitySuccessMessage.action",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/DeleteEntityFailureMessage.action",
    "_Type": "Action.Type.ODataService.DeleteEntity"
}