{
    "ActionResult": {
        "_Name": "CreateMeterReading"
    },
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": {
        "EntitySet": "MeterReadings",
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {
        "MeterReadingDocID": "#Property:DocID",
        "Register": "#Property:RegisterNum",
        "MeterReadingDate": "/SAPAssetManager/Rules/Meter/CurrentDate.js",
        "MeterReadingTime": "/SAPAssetManager/Rules/Meter/CurrentTime.js",
        "DateMaxRead": "/SAPAssetManager/Rules/Meter/PeakDate.js",
        "TimeMaxReading": "/SAPAssetManager/Rules/Meter/PeakTime.js",
        "ActualMeterReadingDate": "/SAPAssetManager/Rules/Meter/CurrentDate.js",
        "ActualMeterReadingTime": "/SAPAssetManager/Rules/Meter/CurrentTime.js",
        "MeterReadingRecorded": "/SAPAssetManager/Rules/Meter/ReadingValueAsDouble.js",
        "MeterReaderNote": "/SAPAssetManager/Rules/Meter/Reading/ReadingNoteValue.js",
        "MeterReadingReason": "/SAPAssetManager/Rules/Meter/Reading/ReadingReasonValue.js",

        "PreviousReadingFloat": "/SAPAssetManager/Rules/Meter/PreviousReadingFloat.js",
        "PreviousReadingDate": "/SAPAssetManager/Rules/Meter/PreviousReadingDate.js",
        "PreviousReadingTime": "/SAPAssetManager/Rules/Meter/PreviousReadingTime.js"
    },
    "Headers":
    {
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "#Property:BatchEquipmentNum",
        "transaction.omdo_id": "/SAPAssetManager/Rules/Meter/Reading/ReadingTransactionMdoHeader.js"
    },
    "CreateLinks":
    [{
        "Property": "Device_Nav",
        "Target":
        {
            "EntitySet": "Devices",
            "ReadLink": "#Property:DeviceLink/#Property:@odata.readLink"
        }
    }],
    "ValidationRule": "/SAPAssetManager/Rules/Meter/CreateUpdate/MeterReadingCreateUpdateValidation.js"
}
