{
    "Actions": "/SAPAssetManager/Rules/Meter/CreateUpdate/MeterReadingsCreateUpdateChangeSetActions.js",
    "OnSuccess": "/SAPAssetManager/Rules/Meter/CreateUpdate/MeterReplaceInstall.js",
    "OnFailure" : "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnFailure.js",
    "Target": {
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "_Type": "Action.Type.ODataService.ChangeSet"
}