{
    "CancelPendingActions": false,
    "DismissModal": "Action.Type.ClosePage.Completed",
    "_Type": "Action.Type.ClosePage",
    "OnSuccess": "/SAPAssetManager/Actions/Parts/PartReturnSuccess.action"
}