{
    "Message": "$(L,confirm_remove_expenses)",
    "OKCaption": "$(L,continue_text)",
    "CancelCaption": "$(L,cancel)",
    "OnOK": "/SAPAssetManager/Rules/Expense/List/RemoveChanges.js",
    "_Type": "Action.Type.Message"
}