{
    "_Type": "Action.Type.Message",
    "Title": "$(L, confirm_status_change)",
    "Message": "$(L, complete_suboperation_warning_message)",
    "OKCaption": "$(L,yes)",
    "CancelCaption": "$(L,no)"
}