{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/InspectionCharacteristics/Update/InspectionCharacteristicsFDCUpdate.page",
    "ModalPage": true,
    "ModalPageFullscreen": true
}
